# Generated by Django 5.0.4 on 2024-05-09 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_suscripcion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_suscripcion', models.CharField(max_length=20)),
                ('precio_suscripcion', models.IntegerField()),
                ('descripcion_suscripcion', models.CharField(max_length=100)),
            ],
        ),
    ]
