# Generated by Django 5.0.4 on 2024-05-12 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_productos_suscripcion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suscripcion',
        ),
    ]
