# Generated by Django 5.0.4 on 2024-05-12 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0003_delete_suscripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_suscripcion', models.CharField(max_length=20)),
                ('precio_suscripcion', models.IntegerField()),
                ('descripcion_suscripcion', models.CharField(max_length=100)),
            ],
        ),
    ]
