# Generated by Django 5.0.4 on 2024-05-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='administracion_campañas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='asistencia_personalizada',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='cantidad_panfletos',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='creacion_avisos',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='creacion_pagina_web',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='diseño_banners',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='monitoreo_optimizacion',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='promocion_google_ads',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
