# Generated by Django 5.0.4 on 2024-05-16 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_suscripcion_administracion_campañas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suscripcion',
            name='descripcion_suscripcion',
        ),
    ]
